
 ItemTraitEnum(THROWABLE)
 ItemTraitEnum(PICKABLE) 
 ItemTraitEnum(CONSUMABLE)
 ItemTraitEnum(EXPLODESONHIT) 
 ItemTraitEnum(STINKS)
 ItemTraitEnum(MELEE) 
 ItemTraitEnum(ALARM)
 ItemTraitEnum(PHYSICALLYDAMAGEABLE) 
 ItemTraitEnum(TOILET) 
 ItemTraitEnum(HOLDANDSHOOT)
 ItemTraitEnum(HEALTHBOOST)